### ISSUE TITLE
before event checklist

### ISSUE THREAD

**Issue by TimDaub** [strikedao/strikedao.com#153]
- [x] voteBegin is set correctly
- [x] bundle.js is minified and recently built with npm run build:frontend
- [x] voting page redirects to /lock
- [x] /result page has video that doesn't give away result
